---
- name: Print ubuntu codename and informations
  debug:
    msg: "{{ ansible_distribution }} {{ ansible_distribution_release }} {{ ansible_distribution_version }}"

- name: Upgrade all packages on servers
  apt:
    upgrade: dist
    update_cache: true
    # cache_valid_time: 3600
    force_apt_get: yes

- name: Install base packages
  apt:
    force_apt_get: true
    name: "{{ item }}"
    state: present
  loop: "{{ ubuntu.packages.prereq|flatten }}"
